shared:
  links:
    about: '#'
    cite: '#'
    contact: 'mailto:contacto@teresIA.es'
    facebook: '#'
    github: 'https://github.com/proyectoTeresIA'
    help: '#'
    help_annotator: '#'
    help_mappings: '#'
    help_ontology_browse: '#'
    help_projects: '#'
    help_recommender: '#'
    help_search: '#'
    help_slice: '#'
    metrics: '#'
    mission: '#'
    privacy_policy: '#'
    rest_api: '/documentation'
    team: '#'
    terms: '#'
    twitter: '#'
    virtual_appliance: '#'
    widgets: '#'
    wiki: '#'

development:
  google_analytics:
    tag_id: null
  links:
    cookies: '#'
    release_notes: 'https://github.com/proyectoTeresIA/portal/releases'
  purl:
    enabled: false
    host: 'purl.bioontology.org'
    prefix: 'https://purl.bioontology.org/ontology'

test:
  google_analytics:
    tag_id: null
  purl:
    enabled: false
    host: 'stagepurl.bioontology.org'
    prefix: 'https://stagepurl.bioontology.org/ontology'

staging:
  google_analytics:
    tag_id: 'G-KF3SKHPEGW'
  links:
    cookies: 'https://www.bioontology.org/terms/#use-of-cookies'
    release_notes: 'https://github.com/proyectoTeresIA/portal/releases'
  purl:
    enabled: false
    host: 'stagepurl.bioontology.org'
    prefix: 'https://stagepurl.bioontology.org/ontology'

production:
  google_analytics:
    tag_id: 'G-KF3SKHPEGW'
  links:
    cookies: 'https://www.bioontology.org/terms/#use-of-cookies'
    release_notes: 'https://github.com/proyectoTeresIA/portal/releases'
  purl:
    enabled: false
    host: 'purl.bioontology.org'
    prefix: 'https://purl.bioontology.org/ontology'

appliance:
  google_analytics:
    tag_id: null
  links:
    cookies: 'https://www.bioontology.org/terms/#use-of-cookies'
    release_notes: 'https://github.com/proyectoTeresIA/portal/releases'
  purl:
    # Set enabled to true if you're running a PURL server to provide PURLs for ontologies and concepts
    # in your OntoPortal instance
    enabled: false
    host: 'purl.example.org'
    # PURL URLs are generated using the prefix + the ontology acronym
    prefix: 'https://purl.example.org/ontology'
